summary: "fetch Data"
description: "fetch coupons and offers of pizza based on category topping from database"
consumes: 
- "application/json"
produces:
- "application/json"

responses:
  405:
    description: "Invalid request"
