summary: "fetch Data"
description: "fetch coupons and offers of pizza deals from database"
consumes: 
- "application/json"
produces:
- "application/json"
parameters:
- in: "body"
  name: "body"
  description: "Accepts the company name, discount type, category and category type"
  required: true
  schema: 
    type: "object"
    properties: 
      company: 
        type: "string"
        format: "str"
        example: "dominos"
      discountType:
        type: "string"
        format: "str"
        example: "COUPON"
      category:
        type: "string"
        format: "str"
        example: "topping"
      categoryType:
        type: "string"
        format: "str"
        example: "oneTopping"


responses:
  405:
    description: "Invalid Input"
